#!/bin/bash

set -e

cd $(dirname $0)

if [ -f .env ]; then
  source .env
fi

if [ "$VERIFY_HOME" = "true" ]; then
  VERIFICATION_RPC_URL="$HOME_RPC_URL"
  VERIFICATION_ETHERSCAN_API_KEY="$HOME_EXPLORER_API_KEY"
else
  VERIFICATION_RPC_URL="$FOREIGN_RPC_URL"
  VERIFICATION_ETHERSCAN_API_KEY="$FOREIGN_EXPLORER_API_KEY"
fi

VERIFICATION_CHAIN_ID=$(RPC_URL="$VERIFICATION_RPC_URL" node getChainId.js) \
VERIFICATION_RPC_URL="$VERIFICATION_RPC_URL" \
VERIFICATION_ETHERSCAN_API_KEY="$VERIFICATION_ETHERSCAN_API_KEY" \
truffle run verify $@ --network for_etherscan_verification
