name: release

on:
  release:
    types: [created]

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        if: ${{ !steps.yarn-cache.outputs.cache-hit }}
      - run: yarn compile
      - run: zip contracts $(find contracts -name '*.sol')
      - run: zip artifacts $(find build -name '*.json')
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: contracts.zip
          asset_name: omnibridge-nft-contracts-${{ steps.get_release.outputs.tag_name }}.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: artifacts.zip
          asset_name: omnibridge-nft-artifacts-${{ steps.get_release.outputs.tag_name }}.zip
          asset_content_type: application/zip
